model_list:
  - model_name: claude-Sonnet-4.5
    litellm_params:
      model: openai/Claude-Sonnet-3.5
      api_base: https://aiproxy.want.biz/v1
      api_key: any
      extra_headers:
        x-client-id: "antigravity"
        origin: "https://aiproxy.want.biz"
        referer: "https://aiproxy.want.biz/"
        user-agent: "Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.5 Mobile/15E148 Safari/604.1"
  - model_name: claude-sonnet-4-5-20250929
    litellm_params:
      model: openai/Claude-Sonnet-3.5
      api_base: https://aiproxy.want.biz/v1
      api_key: any
      extra_headers:
        x-client-id: "antigravity"
        origin: "https://aiproxy.want.biz"
        referer: "https://aiproxy.want.biz/"
        user-agent: "Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.5 Mobile/15E148 Safari/604.1"
  - model_name: claude-haiku-4-5-20251001
    litellm_params:
      model: openai/Claude-3-Haiku
      api_base: https://aiproxy.want.biz/v1
      api_key: any
      extra_headers:
        x-client-id: "antigravity"
        origin: "https://aiproxy.want.biz"
        referer: "https://aiproxy.want.biz/"
        user-agent: "Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.5 Mobile/15E148 Safari/604.1"

litellm_settings:
  drop_params: true
